### ISSUE TITLE
mistake in  Fangying triggerable

### ISSUE THREAD

**Issue by lwtmusou** [Kouchya/TouhouKeireikaku#10]
https://github.com/obstudio/TouhouKeireikaku/blob/29d686ae10fa2a4d34372241a06285f234dce123/src/package/thstandard.cpp#L1983

随便看了一下，技能本身好不好我就不评价了。
代码上，triggerable写错了，有三个小问题。

1 没有检测要收的锦囊是不是零牌转化
2 没有检测该锦囊所在区域。  @曹操奸雄吸牌
3  没有考虑有复数个同技能同时存在的情况
获得牌类的效果很容易忽视以上几项。

**Comment by Kouchya** [comment]
谢谢指正！不愧是前辈，一针见血⊙o⊙
其实最初设计技能的时候是在好几年前，现在看来不少设计不尽如人意。最近在考虑重做或改动不少角色的技能，这个技能也会在重做之列。到时候写新技能代码我会留心这几项的。>v<
