### ISSUE TITLE
effec改为cost

### ISSUE THREAD

**Issue by lwtmusou** [Kouchya/TouhouKeireikaku#12]
https://github.com/obstudio/TouhouKeireikaku/blob/7ab78e37d384f6ad81be037398508f55acbc46fc/src/package/thstandard.cpp#L2723

这种技能发动与否的标志 就是“使用一张牌”的 就该作为cost 
当然，不考虑后续国战机制的话，effect也问题不大。。。

**Comment by Kouchya** [comment]
谢谢指正！您说的没错，EventPhaseEnd那个时机应该写在cost里的，我当时图省事就跟另两个时机写一块儿了。。。
