### ISSUE TITLE
“此牌不能被响应”最好认牌，不要认人

### ISSUE THREAD

**Issue by lwtmusou** [Kouchya/TouhouKeireikaku#13]
https://github.com/obstudio/TouhouKeireikaku/blob/e4d55c2dd6a90396b5e3e7e413ca8a83458d4072/src/server/room.cpp#L1391

"CannotResponse" 的flag清理放在cardfinish。。。要是中间插一个新的pattern的话，
你就需要保证所有插入的pattern都是“@@”类。否则这个新pattern也无法执行。
这个我觉得很难保证所有pattern都是@@类

举两个例子
1 你这里被借刀者 不能使用杀，只能给刀

2 比如 xx： 你受到伤害后， 你可以发动技能 视为使用【南蛮入侵】。
这个南蛮本身也成了一张不能响应的牌。

倒不是说鼓励设计时出现这类插入，只是举例说明这个实现对于此类插入是比较脆弱的。

稳妥的做法还是转义为：
“你的杀不能被闪响应”“你的普通锦囊不能被无懈响应”

可以参考一下神杀马超铁骑，以前那个sp吕蒙
这类实现应该是  根本没进到askforcard里面。

**Comment by Kouchya** [comment]
关于第一个例子：我的确是这么打算的。。。
第二个例子有点麻烦。。。我还是再考虑一下吧
（一开始就是设计成“杀不能被闪响应”“普通锦囊不能被无懈”，后来觉得这么做强度低而且无聊所以就做成了这样）

**Comment by lwtmusou** [comment]
自己的感觉是不能响应 搞成村规不可怕。前提是要 1 定义规范化，且定义能被玩你游戏的玩家接受  2 结算问题要过关
但自己觉得（和程序实现困难与否无关），这个结算似乎在规则层面是无法完美解释的。

另外 不知道你是怎么判断无聊这个问题。个人觉得强命也没啥。
作为体系而言，效果朴素点的将是肯定有必要的。是一个体系稳定的基石。
想玩点花，触发条件和 消耗上做些花样 做做花样，改观所谓无聊的感觉。
只要做好各种梗重复度查证的问题就行了。
每个将都想在效果上标新立异，就怕是神仙打架（非强度，而是指互动外联的安排）

嘛，纯设计层面的东西，我也不便多插嘴。我就提出这个例子，给你参考下。

**Comment by Kouchya** [comment]
暂时改成: 在卡牌包代码里通过判断是否有CannotResponse flag来决定是否askForCard 或 askForUseCard, 这样应该可以防止上述第二个例子的情形了. 

但这样其实还是有一些结算问题, 比如蕾米莉亚对A使用一张牌, 发动誓灵, 这时候B通过技能, 在此牌结算结束前对A使用了另一张牌, A仍然无法响应. 这种情况我暂时考虑的解决方案是: 1. 尽量避免出现插入使用牌结算的情况; 2. 考虑在卡牌包代码里判断: 有flag则在跳过askForCard之后把flag去掉 (个人不太情愿这样); 3. 给蕾米莉亚使用的那张牌加个flag, 而不是给目标角色 (可能这是前辈issue标题的意思? ).

**Comment by lwtmusou** [comment]
不明白你说的【卡牌包】是什么位置。

我的意思是 只用给牌加flag。然后根据flag判断是否直接就不询问askForCard 或 askForUseCard。
看字面就是你说的3.

这种思想也是当前神杀 铁骑的实现思想。

如果还要区分只是特定角色不能响应，
最傻瓜的办法应该是牌的flag里也写入palyer的name作为信息



这种思路下，不应该会产生你说的

[A不能响应牌a，也不能响应中途插入的牌b]
牌b上不可能有关联flag的话，自然也不可能会跳过askforcard了。

**Comment by lwtmusou** [comment]
这里多嘴闲扯两个题外话。
1 对card加flag时的函数选择
我现在的感觉是直接用card的setflag
最好不要用room的setcardflag


本来系统在gamerule是有设置的，使用事件完成后(CardFinish)，会clear这张牌上的flag。

但我遇到过bug。
体现为：a 如果先有曹操奸雄类，把处理区的use.card拿到手上。
 b 奸雄类同一时机下，后触发一个效果，给use.card加上一个flag A
c 曹操使用奸雄牌时，use.card仍附带有之前的flag（这已经是一个新的使用事件了）

b 和 a 换个顺序，则c时没有flag。
我没有debug逐行跟数据，初步怀疑是 看似同一个use.card，但内存不一致。

**Comment by lwtmusou** [comment]
2 设计元素的成本问题
 
 很多看似“创新”的东西在我这里评价不高。
理由不是说不鼓励创新，做东西必然要要衡量创新的成本。
值不值得为这个创新 去打破现有的东西（付出成本）。

像这个例子，在代码实现层面纠结，在规则解释层面也纠结。

判定为值得的例子：
 2-a有着独特，良好的体验感  无可替代性
    比如这个例子，正常情况下，也就多出了aoe时不能打出而已，无可替代性不足。
 2-b有着良好自洽性（不需要“本意”来大量进行特殊例子说明）
    反例：你可令此判定后续执行相反效果。 （蔡文姬悲歌类表示mmp）
 2-c 具有推广到其他设计上的价值，而不是干一票就拉到的噱头
   （比如军争推出连环概念，后续设计都能用得上。

**Comment by Kouchya** [comment]
抱歉两个月没处理了 忘了还有issue。。。现在机制已经改成给牌上flag了

另外 我也赞同前辈对设计元素的理念（这也是为什么我觉得网上有些别的杀不忍直视） 这次蕾米的技能原本是定为不能被闪和无懈响应的 不过因为强度低以及时间不够<del>以及懒惰</del>等原因就原地强化成这样了（手动笑哭

非常感谢前辈的指导 以后我会避免这类设计的 所幸的是目前蕾米技能暂时没出现游戏性上的异常<del>所以请允许我再偷次懒不改了吧</del>

**Comment by lwtmusou** [comment]
嘛，设计这东西，毕竟是你的mod，我也就是建议而已，决策肯定是你自己做。
其实 无法响应这个玩意儿，引申到设计上，本质其实就是很多diyer都不太注意的 
"结算可穷举"问题。

至于实现层面，那个给card上flag,我看了一下，貌似是耦合到 南蛮 万剑里了。 不加类似需要被动响应的新牌的话，也没啥了。
如果要解耦，也就只有扩展askForCard函数，把card（南蛮）作为askForcard的reason传进去，然后检测reason， 由askForCard返回空值。
