### ISSUE TITLE
想知道这种技能的ai怎么做

### ISSUE THREAD

**Issue by Kouchya** [Kouchya/TouhouKeireikaku#14]
其他角色的出牌阶段结束时，若其体力值大于你，你可以将一张手牌当作其本阶段使用的第一张基本牌或普通锦囊牌。

当满足发动时机时，ai需要判断是否将一张手牌视为相应的牌（下称牌A）使用。判断某张特定的手牌的牌面价值是否大于牌A是容易的（粗略地用getUseValue），但为了精确判断是否使用这张牌，还得判断场上是否有ai希望当作牌A目标的角色。然而现在的SmartAI好像并没有以牌名为参数寻找合适目标的函数，所以这点有什么好的解决方案吗？还是说，只能对牌名进行if...elseif穷举，复制standard-cards.ai里的代码。。。

@lwtmusou

**Comment by lwtmusou** [comment]
神杀这种基于规则的ai。。。改到最后，我都快弃疗了。
言归正传，首先就是一个askForUse询问？
1）
 去判断 【值不值得把牌A转化为牌B】这个部分确实没辙。要比较两个牌实际使用的价值是很困难的。
一般来说我也只做了 你所有手牌里选择价值最低的转化成牌B。

2）
但【调用当前已有的函数，把牌B用出来】还是很容易的。 dummyuse 你参照参照呗。东方杀的骚灵ai你看看吧 和你讲的这个技能是同一类

**Comment by Kouchya** [comment]
已经实现了，谢谢前辈>v<
