### ISSUE TITLE
其实不算大事，把我的名字改一下吧

### ISSUE THREAD

**Issue by lwtmusou** [Kouchya/TouhouKeireikaku#8]
居然发现有人用touhoukill做base写 类三国杀题材的mod。受宠若惊。。。
不过我开头首字母是 L 貌似打成了 I 。 囧

**Comment by Kouchya** [comment]
抱歉打错名字，已经修正了。
（一直仰慕的前辈能亲自造访，超兴奋≥▽≤）

**Comment by lwtmusou** [comment]
其实我是现在更偏设计，程序也算是在咬牙做。不过神杀底层已经动了不少东西，但是也没留什么说明，（因为一直就是自己用一下。），你可能需要适应。。。
