### ISSUE TITLE
触发技的记录尽量写到record里

### ISSUE THREAD

**Issue by lwtmusou** [Kouchya/TouhouKeireikaku#9]
你也应该看出来了touhoukill触发技是改过的。是用的国战的逻辑。
最初的原因是因为考量到“同一个人双技能重叠在同一个时机，选择技能发动的情况”
比如 司马懿+郭嘉
所以像你那个FengmoClear 这种清除记录的不要进 triggerable和effect
若真是不巧，极端情况下，这个有同时机技能触发，则会弹出选择“技能发动顺序”的框。

**Comment by Kouchya** [comment]
谢谢前辈指教>v<
大部分技能的clear部分按你说的改过了，灵梦的技能因为要完全重做所以就先没改
